### ISSUE TITLE
error with compile

### ISSUE THREAD

**Issue by feedb** [itaymigdal/LOLSpoof#1]
i compile: nim c LOLSpoof.nim
and view error:
LOLSpoof.nim(91, 9) Error: expression cannot be cast to 'LPCVOID'

**Comment by cookpoo78** [comment]
Hey, it's me from my work account. 
I used Nim 1.6, I know that Nim 2.X caused compilation issues in my other projects. 
Try to use the binary under releases or compile with Nim 1.6

**Comment by feedb** [comment]
Yes, nim 2.2. install nim 1.6 and compile )
